# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-16 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='lock_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='lock_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
